#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

case "$1" in
# Copy file name to clipboard
"x")
      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
# Copy png file to clipboard
"C-c")
      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
# Delete files
"d")
      response=$(echo -e "No\nYes" | dmenu -l 2 -p "Do you want to continue:" -i)
         if [[ "$response" == "Yes" ]]; then
             while read file; do rm "$file" ; done
             else
             echo "no"
         fi ;;
# Open file info in a new terminal
"C-e")
      while read file; do xterm -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
# Open in GIMP
"C-g")
      tr '\n' '\0' | xargs -0 gimp & ;;
# Open file in inkscape
"C-r")
      while read file; do inkscape "$file" & done ;;
# Rotate image -90 degree
"C-comma")
  rotate 270 ;;
# Rotate image 90 degree
"C-period")
 rotate  90 ;;
# Rotate image 180 degree
"C-slash")
  rotate 180 ;;
esac

